In [1]:
import scripts.data_prep as data_prep

In [2]:
# Input the file paths here

raster_path = "/application/pi/Desktop/all imp data/k19-07024.tif"
vector_path = "/application/pi/Desktop/adi_budnip/WinterWheat.shp"

In [3]:
data = data_prep.make_dataframe_with_bands(vector_path,raster_path)

/application/pi/anaconda3/envs/env_adi_2/lib/python3.8/site-packages/pyproj/crs.py:77: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))

In [4]:
data[data['isWheat']==1]

,B1,B2,B3,B4,B5,B6,B7,B8,B9,B10,B11,B12,isWheat
2966,250,256,331,326,599,901,1097,1023,1248,1476,974,620,1
2967,250,272,328,357,599,901,1097,964,1248,1476,974,620,1
5702,205,210,278,232,414,1027,1220,1196,1322,1356,695,400,1
5703,205,228,313,342,509,700,825,818,916,1356,740,497,1
5704,205,255,324,366,509,700,825,825,916,1356,740,497,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6343877,226,449,680,847,1256,1754,1930,2236,2250,2970,2091,1388,1
6346611,401,564,779,1074,1210,1646,1992,1892,2124,3267,2241,1508,1
6346612,401,556,767,1058,1210,1646,1992,1824,2124,3267,2241,1508,1
6346613,317,525,745,1019,1210,1804,2065,1824,2308,3593,2116,1335,1
6349350,317,488,700,978,1210,1804,2065,1816,2308,3593,2116,1335,1

In [5]:
data['NDVI'] = (data.B8-data.B4)/(data.B8+data.B4)

In [10]:
for i in range(1,13):
    for j in range(1,13):
        if i>j:
            BA = 'B'+str(i)
            BB = 'B'+str(j)
            B_net = BA + BB
            data[B_net] =(data[BA]-data[BB])/(data[BB]+data[BA])

In [12]:
data['B8B4'] # this is the one for NDVI

0          0.295615
1          0.314835
2          0.557119
3          0.792483
4          0.760622
             ...
6352572    0.331370
6352573    0.332027
6352574    0.333333
6352575    0.319040
6352576    0.326713
Name: B8B4, Length: 6352577, dtype: float64